### ISSUE TITLE
Documentation Contents

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/BB-TR-Kaynak#18]
### TODO

- [ ] Contributing File 
- [ ] Development File
- [ ] Branch Organization File
- [ ] Semantic Commit Messages File
- [ ] Folder Structure File
- [ ] Content Style Guide File
- [ ] Using Components File
- [ ] Pull Request File
- [ ] Types of contributions File
- [ ] Support File

**Comment by ziarparvaiz** [comment]
Contributing File => @b-tekinli & @TalhaAksoy 
Development File => @ziarparvaiz 
Branch Organization File => @Burak-Atak & @TalhaAksoy 
Semantic Commit Messages File => @ziarparvaiz 
Folder Structure File => @ziarparvaiz 
Content Style Guide File => @b-tekinli & @TalhaAksoy 
Using Components File => @ziarparvaiz 
Pull Request File => @b-tekinli & @TalhaAksoy 
Types of contributions File => @ziarparvaiz 
Support File => @ziarparvaiz
