### ISSUE TITLE
Corrected the structure a little

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/BB-TR-Kaynak#2]
### 📝 Todo

- [x] Pull Request Template
- [x] Auto Assignees 
- [x] Dependency Review
- [x] Greet Message = issue
- [x] Labels
- [x] README.MD
- [x] Favicon, Logos, Slash-Introducing
- [x] [Recognize All Contributors](https://allcontributors.org/)
- [x] Documentation folder & sidebar system
- [x] Sass
- [x] Footer
- [x] Only enable Dark mode
- [x] Announcement Bar 
- [x] Navbar Icon
