### ISSUE TITLE
Home Page & with the components

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/BB-TR-Kaynak#6]
### 📝 Todo

- [x] Home Page Header Component
- [x] Lessons Component
- [x] Lesson Card Component
- [x] Discord Card Component
- [x] Community Component
- [x] Community Card Component
- [x] Algorithm, Data Structure & GIT Folders
- [x] Header Item
- [x] Footer Item
