### ISSUE TITLE
Global style and CSS variable

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/BB-TR-Kaynak#7]
### TODO

- [x] Global style theme dark
- [x] Container class
- [x] CSS color variable
- [x] CSS global variable
